# Generated by Django 5.1.1 on 2024-09-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment',
            field=models.CharField(choices=[('D', 'Not Recommended'), ('N', 'Neutral'), ('R', 'Recommended')], default='D', max_length=1),
        ),
    ]
